import Navbar from '@/components/Navbar/Navbar';
import type { Metadata } from 'next';
import { Barlow } from 'next/font/google';
import { SkeletonTheme } from 'react-loading-skeleton';
import 'react-loading-skeleton/dist/skeleton.css';
import './globals.scss';

const barlow = Barlow({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <SkeletonTheme baseColor="#19214250" highlightColor="#1e284f50">
          <Navbar />
          {children}
        </SkeletonTheme>
      </body>
    </html>
  );
}
